spring.application.name=Gateway

server.port=7777

logging.level.org.springframework.cloud.gateway=DEBUG

#Eureka ??? ?????? ??
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


#?? ??? ?? ???? ?? ?? ??? ??
#-------------------------------------------
# Product Service
#-------------------------------------------
spring.cloud.gateway.server.webflux.routes[0].id=productservice
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:7771
spring.cloud.gateway.server.webflux.routes[0].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[0].predicates[0].args.pattern=/productapp/**


#-------------------------------------------
# Order Service
#-------------------------------------------
spring.cloud.gateway.server.webflux.routes[1].id=OrderService
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:7772
spring.cloud.gateway.server.webflux.routes[1].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[1].predicates[0].args.pattern=/orderapp/**

#-------------------------------------------
# Member Service
#-------------------------------------------
spring.cloud.gateway.server.webflux.routes[2].id=MemberService
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:7773
spring.cloud.gateway.server.webflux.routes[2].predicates[0].name=Path
spring.cloud.gateway.server.webflux.routes[2].predicates[0].args.pattern=/memberapp/**

#Sprng Gateway? /memberapp/** ? ??? ??? MemberService? ???? URL ????(memberapp) ????
spring.cloud.gateway.server.webflux.routes[2].filters[0].name=StripPrefix
spring.cloud.gateway.server.webflux.routes[2].filters[0].args.parts=1
